<?php

/**
 * @file
 * Tide Event ATDW.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\node\NodeTypeInterface;
use Drupal\tide_event_atdw\Plugin\migrate\source\AtdwEvent;

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * @see \Drupal\node\NodeTypeForm::form()
 */
function tide_event_atdw_form_node_type_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  /** @var \Drupal\node\NodeTypeInterface $type */
  $type = $form_state->getFormObject()->getEntity();
  if ($type->get('type') !== 'event') {
    return;
  }

  $form['tide_event_atdw'] = [
    '#type' => 'details',
    '#title' => t('ATDW Integration'),
    '#group' => 'additional_settings',
  ];

  $api_key = \Drupal::config('tide_event_atdw.settings')->get('api_key');
  $form['tide_event_atdw']['tide_event_atdw_api_key'] = [
    '#type' => 'textfield',
    '#description' => t('This API key is used to import events from Australian Tourism Data Warehouse.'),
    '#title' => t('API Key'),
    '#default_value' => $form_state->getValue('tide_event_atdw_api_key', $api_key),
  ];

  $state = \Drupal::config('tide_event_atdw.settings')->get('state');
  $form['tide_event_atdw']['tide_event_atdw_state'] = [
    '#type' => 'select',
    '#title' => t('State'),
    '#options' => [
      '' => t('All states/territories'),
      'ACT' => t('Australian Capital Territory'),
      'NSW' => t('New South Wales'),
      'NT' => t('Northern Territory'),
      'QLD' => t('Queensland'),
      'SA' => t('South Australia'),
      'VIC' => t('Victoria'),
      'TAS' => t('Tasmania'),
      'WA' => t('Western Australia'),
    ],
    '#default_value' => $form_state->getValue('tide_event_atdw_state', $state),
  ];

  $category = \Drupal::config('tide_event_atdw.settings')->get('category');
  if (!$category) {
    $category = 'EVENT';
  }
  $form['tide_event_atdw']['tide_event_atdw_category'] = [
    '#type' => 'textfield',
    '#title' => t('Category'),
    '#default_value' => $form_state->getValue('tide_event_atdw_category', $category),
  ];

  /** @var \Drupal\tide_site\TideSiteHelper $site_helper */
  $site_helper = \Drupal::service('tide_site.helper');
  $sites = $site_helper->getAllSites();
  $site_list = ['' => t('- Select a site -')];
  foreach ($sites as $site) {
    $site_list[$site->getName()] = $site->getName();
  }
  $default_site = \Drupal::config('tide_event_atdw.settings')->get('default_site');
  $form['tide_event_atdw']['tide_event_atdw_default_site'] = [
    '#type' => 'select',
    '#title' => t('Default site for imported events'),
    '#description' => t('All imported events will belong to this default site.'),
    '#options' => $site_list,
    '#default_value' => $default_site,
  ];

  $post_import = \Drupal::config('tide_event_atdw.settings')->get('post_import');
  if (!$post_import) {
    $post_import = 'keep';
  }
  $form['tide_event_atdw']['tide_event_atdw_post_import'] = [
    '#type' => 'select',
    '#title' => t('Previously imported events'),
    '#description' => t('Select what to do with items that were previously imported, but are now no longer in ATDW data.'),
    '#options' => [
      AtdwEvent::POST_IMPORT_ACTION_KEEP => t('Keep'),
      AtdwEvent::POST_IMPORT_ACTION_ARCHIVE => t('Archive'),
      AtdwEvent::POST_IMPORT_ACTION_ROLLBACK => t('Delete'),
    ],
    '#default_value' => $form_state->getValue('tide_event_atdw_post_import', $post_import),
  ];

  $form['#entity_builders'][] = 'tide_event_atdw_form_node_type_form_submit';
}

/**
 * Submit callback.
 *
 * @param string $entity_type
 *   Entity type.
 * @param \Drupal\node\NodeTypeInterface $type
 *   Node type.
 * @param array $form
 *   Form array.
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *   Form state.
 */
function tide_event_atdw_form_node_type_form_submit($entity_type, NodeTypeInterface $type, array $form, FormStateInterface $form_state) {
  $settings = \Drupal::configFactory()->getEditable('tide_event_atdw.settings');
  $api_key = $form_state->getValue('tide_event_atdw_api_key');
  $state = $form_state->getValue('tide_event_atdw_state');
  $category = $form_state->getValue('tide_event_atdw_category');
  $post_import = $form_state->getValue('tide_event_atdw_post_import');
  $default_site = $form_state->getValue('tide_event_atdw_default_site');
  $settings
    ->set('api_key', $api_key)
    ->set('state', $state)
    ->set('category', $category)
    ->set('post_import', $post_import)
    ->set('default_site', $default_site)
    ->save();
}
